# Generated by Django 2.2.14 on 2021-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0005_auto_20210818_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name_plural': 'Blogger Profile'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/post'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.ImageField(upload_to='media/profile'),
        ),
    ]
