# Generated by Django 2.2.14 on 2021-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_auto_20210818_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/post'),
        ),
    ]
