# Generated by Django 2.2.14 on 2021-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0007_auto_20210818_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
