# Generated by Django 2.2.14 on 2021-08-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0008_auto_20210819_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Image',
        ),
    ]
