# Generated by Django 2.2.14 on 2021-08-20 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0009_auto_20210820_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='birth',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
