name: Django CI

on:
  push:
    branches:
      - akash-master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

      - name: Merge to main branch
        if: github.ref == 'refs/heads/feature' && github.event_name == 'push'
        run: |
          git config user.name "akashvats29"
          git config user.email "vatsakash168@gmail.com"
          git checkout master
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'feature' into main"
          git push origin master
