- uses: actions/checkout@v2
  with:
    ref: main

- name: Merge to main branch
  if: github.ref == 'refs/heads/akash-master' && github.event_name == 'push'
  run: |
    git config user.name "akashvats29"
    git config user.email "vatsakash168@gmail.com"
    git checkout main
    git merge --no-ff ${{ github.sha }} -m "Merge branch 'akash-master' into main"
    git push origin main
