name: Automatic Branch Merge

on:
  push:
    branches:
      - main

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "aakash"
          git config user.email "vatsakash168@gmail.com"
          git checkout akash-master
<<<<<<< HEAD
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'main' into 'akash-master'"
=======
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'main' into akash-master"
>>>>>>> 86444cda37a4db819859b26cdbe4a97214887009
          git push origin akash-master

          


