name: Automatic Branch Merge

on:
  push:
    branches:
      - akash-master

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "aakash"
          git config user.email "vatsakash168@gmail.com"
          git fetch origin
          git checkout master
          # git merge --allow-unrelated-histories akash-master
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'akash-master' into 'master'"
          git push origin master

          


