name: Automatic Branch Merge

on:
  push:
    branches:
      - main
      - akash-master

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "aakash"
          git config user.email "vatsakash168@gmail.com"
          git branch
          git config user.name
          git fetch origin
          git branch
          git checkout origin/akash-master
          git branch
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'main' into akash-master"
          git push origin akash-master

          


