name: Automatic Branch Merge

on:
  push:
    branches:
      - akash2

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "aakash"
          git config user.email "vatsakash168@gmail.com"
          git fetch origin
          git checkout akash1
          # git merge --allow-unrelated-histories akash2
          git merge --no-edit akash2
          # git merge --no-ff ${{ github.sha }} -m "Merge branch 'akash2' into 'akash1'"
          git push origin akash1

          





